default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  reconnect: false

development:
  <<: *default
  host: db
  database: development
  username: postgres
  password: postgres

test:
  <<: *default
  host: db
  database: test
  username: postgres
  password: postgres

staging:
  <<: *default
  adapter: postgresql

production:
  <<: *default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  port: <%= ENV['DB_PORT'] %>
  password: <%= ENV['DB_PASSWORD'] %>
