default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  reconnect: false

development:
  <<: *default
  host: db
  database: development
  username: postgres
  password: postgres

test:
  <<: *default
  host: db
  database: test
  username: postgres
  password: postgres

staging:
  <<: *default

production:
  <<: *default
